"""create account table

Revision ID: c3ce99e6ad39
Revises: 
Create Date: 2026-04-23 08:31:47.396022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = 'c3ce99e6ad39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_process_jobs',
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('load_from', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('queued', 'retrying', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('documents',
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_documents_hash'), 'documents', ['hash'], unique=False)
    op.create_table('document_process_job_logs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['document_process_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector', VECTOR(dim=1536), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_embeddings_doc_id'), 'embeddings', ['doc_id'], unique=False)
    op.create_table('file_results',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('parser_name', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('extracted_summary', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['document_process_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'file_path', name='uq_file_results_job_id_file_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synset',
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('lex_filenum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gloss', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_satellite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lex_filenum'], ['lexical_domain.id'], name='synset_lex_filenum_fkey'),
    sa.PrimaryKeyConstraint('offset', 'pos', name='synset_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('lexical_domain',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lexical_domain_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('verb_frame_sense',
    sa.Column('sense_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('frame_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['verb_frame.id'], name=op.f('verb_frame_sense_frame_id_fkey')),
    sa.ForeignKeyConstraint(['sense_id'], ['sense.id'], name=op.f('verb_frame_sense_sense_id_fkey')),
    sa.PrimaryKeyConstraint('sense_id', 'frame_id', name=op.f('verb_frame_sense_pkey'))
    )
    op.create_table('morph_exception',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pos', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('inflected_form', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('base_form', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('morph_exception_pkey'))
    )
    op.create_index(op.f('idx_morph_exc'), 'morph_exception', ['pos', 'inflected_form'], unique=False)
    op.create_table('semantic_relation',
    sa.Column('from_synset_offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_synset_pos', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('to_synset_offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_synset_pos', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_lexical', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source_sense_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_sense_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_synset_offset', 'from_synset_pos'], ['synset.offset', 'synset.pos'], name=op.f('semantic_relation_from_synset_offset_from_synset_pos_fkey')),
    sa.ForeignKeyConstraint(['source_sense_id'], ['sense.id'], name=op.f('semantic_relation_source_sense_id_fkey')),
    sa.ForeignKeyConstraint(['target_sense_id'], ['sense.id'], name=op.f('semantic_relation_target_sense_id_fkey')),
    sa.ForeignKeyConstraint(['to_synset_offset', 'to_synset_pos'], ['synset.offset', 'synset.pos'], name=op.f('semantic_relation_to_synset_offset_to_synset_pos_fkey'))
    )
    op.create_index(op.f('idx_relation_type'), 'semantic_relation', ['relation_type'], unique=False)
    op.create_index(op.f('idx_relation_to'), 'semantic_relation', ['to_synset_offset', 'to_synset_pos'], unique=False)
    op.create_index(op.f('idx_relation_from'), 'semantic_relation', ['from_synset_offset', 'from_synset_pos'], unique=False)
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('word_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('lemma', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pos', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='word_pkey'),
    sa.UniqueConstraint('lemma', 'pos', name='word_lemma_pos_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_word_lemma'), 'word', ['lemma'], unique=False)
    op.create_table('sense',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('synset_offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('synset_pos', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lex_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sense_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sense_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['synset_offset', 'synset_pos'], ['synset.offset', 'synset.pos'], name=op.f('sense_synset_offset_synset_pos_fkey')),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name=op.f('sense_word_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sense_pkey'))
    )
    op.create_index(op.f('idx_sense_word'), 'sense', ['word_id'], unique=False)
    op.create_index(op.f('idx_sense_synset'), 'sense', ['synset_offset', 'synset_pos'], unique=False)
    op.create_index(op.f('idx_sense_key'), 'sense', ['sense_key'], unique=False)
    op.create_table('verb_frame',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('verb_frame_pkey'))
    )
    op.drop_table('file_results')
    op.drop_index(op.f('ix_embeddings_doc_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_table('document_process_job_logs')
    op.drop_index(op.f('ix_documents_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('document_process_jobs')
    # ### end Alembic commands ###
